import type { ScienceBatch13ActivitySeed, ScienceBatch13WaveDefinition } from "./scienceBatch13Authoring";

const STAGE_ID = "science-earth-body-environment";
type O={required?:boolean;difficulty?:1|2|3;ageMin?:number;emoji?:string};
const c=(id:string,p:string,l:string,t:string,d:string,q:string,choices:string[],correct:string,s:string,o:O={}):ScienceBatch13ActivitySeed=>({kind:"choice",id,packId:p,lessonId:l,title:t,description:d,emoji:o.emoji??"🌍",ageMin:o.ageMin??4,ageMax:7,difficulty:o.difficulty??2,requiredForStage:o.required??false,skillId:s,prompt:q,choices,correctChoice:correct});
const m=(id:string,p:string,l:string,t:string,d:string,q:string,s:string,pairs:Array<{left:string;right:string;pair:string}>,o:O={}):ScienceBatch13ActivitySeed=>({kind:"matching",id,packId:p,lessonId:l,title:t,description:d,emoji:o.emoji??"🧩",ageMin:o.ageMin??4,ageMax:7,difficulty:o.difficulty??2,requiredForStage:o.required??false,skillId:s,prompt:q,matchItems:pairs.flatMap(x=>[{label:x.left,pair:x.pair},{label:x.right,pair:x.pair}])});

const earth=[
c("science-earth-sun-day","science.pack.earth-sky-patterns","science-earth-sky-patterns","Matahari dan siang","Menghubungkan cahaya matahari dengan siang hari.","Saat bagian tempat kita berada menghadap Matahari, biasanya kita mengalami apa?",["siang hari","malam hari","musim hujan selalu"],"siang hari","science.earth.sky_patterns.basic",{required:true,ageMin:5}),
c("science-earth-moon-night","science.pack.earth-sky-patterns","science-earth-sky-patterns","Bulan di langit malam","Mengenali benda langit yang sering terlihat malam hari.","Benda langit mana yang sering mudah terlihat pada malam hari?",["bulan","pelangi setiap malam","awan selalu hitam"],"bulan","science.earth.sky_patterns.basic"),
c("science-earth-shadow-sun","science.pack.earth-sky-patterns","science-earth-sky-patterns","Bayangan karena cahaya","Menghubungkan cahaya dengan terbentuknya bayangan.","Apa yang dapat terbentuk saat benda menghalangi cahaya?",["bayangan","suara","rasa manis"],"bayangan","science.earth.sky_patterns.basic"),
c("science-earth-cloud-rain","science.pack.earth-sky-patterns","science-earth-sky-patterns","Awan dan hujan","Menghubungkan awan gelap tebal dengan kemungkinan hujan.","Jika awan makin gelap dan tebal, perubahan cuaca apa yang mungkin terjadi?",["hujan turun","bintang muncul siang hari","tanah langsung membeku"],"hujan turun","science.earth.sky_patterns.basic",{difficulty:3}),
m("science-match-sky-observation-c","science.pack.earth-sky-patterns","science-earth-sky-patterns","Pengamatan langit","Mencocokkan gejala langit dengan kondisi yang relevan.","Pasangkan pengamatan dengan kondisi yang paling sesuai.","science.earth.sky_patterns.basic",[{left:"matahari terang",right:"siang cerah",pair:"day"},{left:"bintang tampak jelas",right:"malam",pair:"night"},{left:"awan gelap tebal",right:"mungkin hujan",pair:"rain"}],{required:true})
];
const body=[
c("science-body-wash-hands","science.pack.body-health-habits","science-body-health-habits","Cuci tangan","Mengenali kebiasaan kebersihan sederhana.","Kapan sebaiknya tangan dicuci dengan sabun?",["sebelum makan","setelah memakai sepatu saja","hanya saat hari Minggu"],"sebelum makan","science.body.health_habits.basic",{required:true}),
c("science-body-teeth-brush","science.pack.body-health-habits","science-body-health-habits","Merawat gigi","Mengenali kebiasaan merawat gigi.","Kebiasaan mana yang membantu menjaga kebersihan gigi?",["menyikat gigi","tidak pernah membersihkan gigi","menggosok gigi dengan pasir"],"menyikat gigi","science.body.health_habits.basic"),
c("science-body-water-drink","science.pack.body-health-habits","science-body-health-habits","Tubuh perlu air","Mengenali air minum sebagai kebutuhan tubuh.","Apa yang membantu tubuh tetap mendapat cairan?",["minum air","memegang batu","melihat televisi"],"minum air","science.body.health_habits.basic"),
c("science-body-sleep-rest","science.pack.body-health-habits","science-body-health-habits","Tidur untuk istirahat","Mengenali tidur sebagai waktu tubuh beristirahat.","Kegiatan mana yang memberi tubuh waktu beristirahat?",["tidur cukup","berlari tanpa berhenti","tidak tidur semalaman"],"tidur cukup","science.body.health_habits.basic"),
m("science-match-body-care-c","science.pack.body-health-habits","science-body-health-habits","Bagian tubuh dan perawatan","Mencocokkan perawatan kebersihan sederhana dengan bagian tubuh.","Pasangkan bagian tubuh dengan kebiasaan perawatannya.","science.body.health_habits.basic",[{left:"tangan",right:"cuci dengan sabun",pair:"hands"},{left:"gigi",right:"sikat gigi",pair:"teeth"},{left:"rambut",right:"cuci dan rapikan",pair:"hair"}])
];
const eco=[
c("science-eco-plant-sun-water","science.pack.ecosystem-dependencies","science-ecosystem-dependencies","Tanaman bergantung pada lingkungan","Mengidentifikasi kebutuhan lingkungan tumbuhan.","Tanaman di kebun membutuhkan kombinasi mana untuk tumbuh?",["air dan cahaya","plastik dan kaca","mainan dan kertas"],"air dan cahaya","science.ecosystem.dependencies.basic",{required:true}),
c("science-eco-bee-flower","science.pack.ecosystem-dependencies","science-ecosystem-dependencies","Lebah dan bunga","Mengenali hubungan hewan dengan sumber makanan.","Mengapa lebah sering mendatangi bunga?",["mencari nektar","mencari batu","mencari plastik"],"mencari nektar","science.ecosystem.dependencies.basic"),
c("science-eco-bird-tree","science.pack.ecosystem-dependencies","science-ecosystem-dependencies","Pohon menjadi tempat hidup","Mengenali tumbuhan sebagai tempat berlindung hewan.","Pohon dapat membantu burung dengan menyediakan apa?",["tempat bertengger atau bersarang","air laut","roda kendaraan"],"tempat bertengger atau bersarang","science.ecosystem.dependencies.basic"),
c("science-eco-food-chain-change","science.pack.ecosystem-dependencies","science-ecosystem-dependencies","Perubahan sumber makanan","Menalar dampak sederhana bila sumber makanan berkurang.","Jika makanan utama suatu hewan sangat berkurang, apa yang mungkin terjadi?",["hewan lebih sulit mendapat makanan","hewan tidak perlu makan lagi","semua benda menjadi hidup"],"hewan lebih sulit mendapat makanan","science.ecosystem.dependencies.basic",{difficulty:3,ageMin:5}),
m("science-match-ecosystem-needs-c","science.pack.ecosystem-dependencies","science-ecosystem-dependencies","Makhluk hidup dan kebutuhannya","Mencocokkan makhluk hidup dengan kebutuhan lingkungan yang relevan.","Pasangkan makhluk hidup dengan kebutuhan yang sesuai.","science.ecosystem.dependencies.basic",[{left:"ikan",right:"air yang sesuai",pair:"fish"},{left:"tanaman",right:"cahaya",pair:"plant"},{left:"burung",right:"tempat bersarang",pair:"bird"}],{difficulty:2})
];
const environment=[
c("science-env-trash-bin","science.pack.environment-care","science-environment-care","Sampah ke tempatnya","Mengenali tindakan menjaga kebersihan lingkungan.","Apa tindakan yang tepat untuk bungkus makanan setelah digunakan?",["buang ke tempat sampah yang sesuai","lempar ke sungai","tinggalkan di jalan"],"buang ke tempat sampah yang sesuai","science.environment.care.basic",{required:true}),
c("science-env-save-water","science.pack.environment-care","science-environment-care","Hemat air","Mengenali tindakan mengurangi pemborosan air.","Apa yang sebaiknya dilakukan saat keran tidak sedang dipakai?",["matikan keran","biarkan terus mengalir","buka semua keran"],"matikan keran","science.environment.care.basic"),
c("science-env-reuse-bottle","science.pack.environment-care","science-environment-care","Gunakan kembali","Mengenali penggunaan ulang sebagai pengurangan sampah.","Mana contoh menggunakan kembali barang?",["memakai botol isi ulang","membuang gelas baru setelah satu teguk","membakar semua kertas"],"memakai botol isi ulang","science.environment.care.basic"),
c("science-env-plant-care","science.pack.environment-care","science-environment-care","Merawat tanaman","Mengenali tindakan sederhana merawat lingkungan hidup.","Tindakan mana yang membantu tanaman di halaman tetap terawat?",["menyiram sesuai kebutuhan","menginjak tanaman","mencabut semua daun setiap hari"],"menyiram sesuai kebutuhan","science.environment.care.basic"),
m("science-match-environment-actions-c","science.pack.environment-care","science-environment-care","Aksi ramah lingkungan","Mencocokkan tujuan dengan tindakan sederhana.","Pasangkan tujuan dengan tindakan yang sesuai.","science.environment.care.basic",[{left:"hemat air",right:"tutup keran",pair:"water"},{left:"kurangi sampah",right:"pakai ulang wadah",pair:"reuse"},{left:"jaga kebersihan",right:"buang sampah pada tempatnya",pair:"clean"}])
];
const measurement=[
c("science-measure-longer-pencil","science.pack.observation-measurement","science-observation-measurement","Bandingkan panjang","Menggunakan perbandingan langsung untuk panjang.","Pensil A lebih panjang dari Pensil B. Mana yang lebih pendek?",["Pensil B","Pensil A","keduanya pasti sama"],"Pensil B","science.observation.measurement.basic",{required:true,ageMin:5}),
c("science-measure-hot-cold","science.pack.observation-measurement","science-observation-measurement","Bandingkan suhu","Membedakan pengamatan panas dan dingin secara kualitatif.","Es terasa dingin dan teh hangat terasa hangat. Mana yang suhunya lebih rendah?",["es","teh hangat","keduanya selalu sama"],"es","science.observation.measurement.basic"),
c("science-measure-more-water","science.pack.observation-measurement","science-observation-measurement","Bandingkan banyak air","Menentukan wadah dengan isi lebih banyak dari informasi eksplisit.","Gelas A berisi lebih banyak air daripada Gelas B. Mana yang isinya lebih banyak?",["Gelas A","Gelas B","tidak ada air"],"Gelas A","science.observation.measurement.basic"),
c("science-observe-record-same-time","science.pack.observation-measurement","science-observation-measurement","Catat pengamatan","Mengenali pencatatan sebagai bagian observasi yang dapat dibandingkan.","Agar perubahan tinggi tanaman bisa dibandingkan, apa yang baik dilakukan?",["catat hasil pengukuran secara teratur","tebak tanpa melihat","ganti tanaman setiap kali mengukur"],"catat hasil pengukuran secara teratur","science.observation.measurement.basic",{difficulty:3,ageMin:5}),
m("science-match-observation-tools-c","science.pack.observation-measurement","science-observation-measurement","Alat dan pengamatan","Mencocokkan alat sederhana dengan hal yang diukur atau diamati.","Pasangkan alat dengan kegunaannya.","science.observation.measurement.basic",[{left:"penggaris",right:"panjang",pair:"length"},{left:"termometer",right:"suhu",pair:"temp"},{left:"gelas ukur",right:"volume cairan",pair:"volume"}],{difficulty:3,ageMin:5})
];

export const SCIENCE_BATCH13_WAVE_C:ScienceBatch13WaveDefinition={wave:"C",stage:{id:STAGE_ID,subjectId:"science",title:"Bumi, Tubuh & Lingkungan",subtitle:"Amati pola langit, rawat tubuh dan lingkungan, pahami ketergantungan makhluk hidup, serta bandingkan hasil pengamatan.",emoji:"🌍"},lessons:[
{id:"science-earth-sky-patterns",subjectId:"science",pathId:"science-discovery-foundations",stageId:STAGE_ID,title:"Bumi dan pola langit",objective:"Menghubungkan pengamatan Matahari, malam, bayangan, dan awan dengan pola sederhana.",ageMin:5,ageMax:7},
{id:"science-body-health-habits",subjectId:"science",pathId:"science-discovery-foundations",stageId:STAGE_ID,title:"Tubuh dan kebiasaan sehat",objective:"Mengenali kebiasaan kebersihan, hidrasi, dan istirahat dasar.",ageMin:4,ageMax:7},
{id:"science-ecosystem-dependencies",subjectId:"science",pathId:"science-discovery-foundations",stageId:STAGE_ID,title:"Ketergantungan makhluk hidup",objective:"Mengenali hubungan sederhana antara makhluk hidup dan sumber daya lingkungannya.",ageMin:4,ageMax:7},
{id:"science-environment-care",subjectId:"science",pathId:"science-discovery-foundations",stageId:STAGE_ID,title:"Menjaga lingkungan",objective:"Memilih tindakan sederhana yang mengurangi sampah dan pemborosan sumber daya.",ageMin:4,ageMax:7},
{id:"science-observation-measurement",subjectId:"science",pathId:"science-discovery-foundations",stageId:STAGE_ID,title:"Observasi dan pengukuran",objective:"Membandingkan panjang, suhu, volume, mencatat pengamatan, dan mengenali alat ukur.",ageMin:5,ageMax:7}
],packs:[
{id:"science.pack.earth-sky-patterns",title:"Earth and Sky Patterns",lessonId:"science-earth-sky-patterns",ageMin:5,ageMax:7},
{id:"science.pack.body-health-habits",title:"Body and Health Habits",lessonId:"science-body-health-habits",ageMin:4,ageMax:7},
{id:"science.pack.ecosystem-dependencies",title:"Ecosystem Dependencies",lessonId:"science-ecosystem-dependencies",ageMin:4,ageMax:7},
{id:"science.pack.environment-care",title:"Environment Care",lessonId:"science-environment-care",ageMin:4,ageMax:7},
{id:"science.pack.observation-measurement",title:"Observation and Measurement",lessonId:"science-observation-measurement",ageMin:5,ageMax:7}],skills:[
{id:"science.earth.sky_patterns.basic",subjectId:"science",title:"Pola Bumi dan langit",description:"Menghubungkan pengamatan langit dan cahaya dengan pola harian serta cuaca sederhana.",domain:"science",ageMin:5,ageMax:7},
{id:"science.body.health_habits.basic",subjectId:"science",title:"Kebiasaan sehat dasar",description:"Mengenali kebiasaan kebersihan, minum, dan istirahat sederhana.",domain:"science",ageMin:4,ageMax:7},
{id:"science.ecosystem.dependencies.basic",subjectId:"science",title:"Ketergantungan ekosistem dasar",description:"Mengenali hubungan sederhana makhluk hidup dengan makanan, air, cahaya, dan habitat.",domain:"science",ageMin:4,ageMax:7},
{id:"science.environment.care.basic",subjectId:"science",title:"Kepedulian lingkungan dasar",description:"Memilih tindakan sederhana untuk menjaga kebersihan dan menghemat sumber daya.",domain:"science",ageMin:4,ageMax:7},
{id:"science.observation.measurement.basic",subjectId:"science",title:"Observasi dan pengukuran dasar",description:"Membandingkan hasil observasi dan mengenali alat ukur sederhana.",domain:"science",ageMin:5,ageMax:7}],activities:[...earth,...body,...eco,...environment,...measurement]};
