import type { ScienceBatch13WaveDefinition } from "./scienceBatch13Authoring";

export const SCIENCE_BATCH13_WAVE_D: ScienceBatch13WaveDefinition = {
  wave: "D",
  stage: {
    id: "science-evidence-review-challenge",
    subjectId: "science",
    title: "Bukti, Pilihan & Tantangan Sains",
    subtitle: "Gunakan pengamatan sederhana untuk memprediksi, memilih, dan menjelaskan dunia sekitar.",
    emoji: "🧪"
  },
  lessons: [
    { id: "science-investigation-evidence", subjectId: "science", pathId: "science-discovery-foundations", stageId: "science-evidence-review-challenge", title: "Penyelidikan & Bukti", objective: "Membuat prediksi dan memilih perbandingan sederhana berdasarkan pengamatan.", ageMin: 5, ageMax: 7 },
    { id: "science-living-adaptations", subjectId: "science", pathId: "science-discovery-foundations", stageId: "science-evidence-review-challenge", title: "Ciri Makhluk Hidup", objective: "Menghubungkan ciri tubuh atau tumbuhan dengan fungsi sederhana pada lingkungan familiar.", ageMin: 5, ageMax: 7 },
    { id: "science-material-design", subjectId: "science", pathId: "science-discovery-foundations", stageId: "science-evidence-review-challenge", title: "Pilih Bahan yang Tepat", objective: "Memilih bahan berdasarkan sifat yang dibutuhkan untuk penggunaan sederhana.", ageMin: 5, ageMax: 7 },
    { id: "science-weather-environment-reasoning", subjectId: "science", pathId: "science-discovery-foundations", stageId: "science-evidence-review-challenge", title: "Cuaca & Lingkungan", objective: "Menghubungkan tanda cuaca dan tindakan sehari-hari dengan akibat yang dapat diamati.", ageMin: 5, ageMax: 7 },
    { id: "science-mixed-review-challenge", subjectId: "science", pathId: "science-discovery-foundations", stageId: "science-evidence-review-challenge", title: "Tantangan Sains Campuran", objective: "Menggunakan konsep hidup, bahan, air, gaya, dan indera dalam soal campuran sederhana.", ageMin: 5, ageMax: 7 }
  ],
  packs: [
    { id: "science.pack.investigation-evidence", title: "Investigation and Evidence", lessonId: "science-investigation-evidence", ageMin: 5, ageMax: 7 },
    { id: "science.pack.living-adaptations", title: "Living Features and Functions", lessonId: "science-living-adaptations", ageMin: 5, ageMax: 7 },
    { id: "science.pack.material-design", title: "Materials for a Purpose", lessonId: "science-material-design", ageMin: 5, ageMax: 7 },
    { id: "science.pack.weather-environment-reasoning", title: "Weather and Environment Reasoning", lessonId: "science-weather-environment-reasoning", ageMin: 5, ageMax: 7 },
    { id: "science.pack.mixed-review-challenge", title: "Mixed Science Review Challenge", lessonId: "science-mixed-review-challenge", ageMin: 5, ageMax: 7 }
  ],
  skills: [
    { id: "science.investigation.evidence.basic", subjectId: "science", title: "Penyelidikan dan bukti dasar", description: "Membuat prediksi dan memilih perbandingan sederhana dari bukti yang dapat diamati.", domain: "science", ageMin: 5, ageMax: 7 },
    { id: "science.living.features_function.basic", subjectId: "science", title: "Ciri dan fungsi makhluk hidup", description: "Menghubungkan ciri familiar hewan atau tumbuhan dengan fungsi sederhananya.", domain: "science", ageMin: 5, ageMax: 7 },
    { id: "science.materials.design_choice.basic", subjectId: "science", title: "Pemilihan bahan dasar", description: "Memilih bahan sesuai sifat yang dibutuhkan untuk penggunaan sehari-hari sederhana.", domain: "science", ageMin: 5, ageMax: 7 },
    { id: "science.weather.environment_reasoning.basic", subjectId: "science", title: "Penalaran cuaca dan lingkungan", description: "Menghubungkan tanda cuaca dan tindakan menjaga lingkungan dengan akibat sederhana.", domain: "science", ageMin: 5, ageMax: 7 },
    { id: "science.mixed_reasoning.review", subjectId: "science", title: "Penalaran sains campuran", description: "Menerapkan beberapa konsep sains dasar dalam tantangan campuran yang terukur.", domain: "science", ageMin: 5, ageMax: 7 }
  ],
  activities: [
    { kind: "choice", id: "science-investigate-plant-light", packId: "science.pack.investigation-evidence", lessonId: "science-investigation-evidence", title: "Bandingkan cahaya tanaman", description: "Pilih hasil yang perlu diamati saat membandingkan cahaya.", emoji: "🌱", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: true, skillId: "science.investigation.evidence.basic", prompt: "Dua tanaman sama diberi air sama, tetapi satu mendapat cahaya dan satu tidak. Apa yang paling tepat dibandingkan setelah beberapa hari?", choices: ["Pertumbuhan tanaman", "Warna pot", "Nama pemilik"], correctChoice: "Pertumbuhan tanaman" },
    { kind: "choice", id: "science-investigate-fair-water", packId: "science.pack.investigation-evidence", lessonId: "science-investigation-evidence", title: "Buat perbandingan adil", description: "Pilih hal yang sebaiknya dibuat sama saat menguji jumlah air.", emoji: "💧", ageMin: 5, ageMax: 7, difficulty: 3, requiredForStage: false, skillId: "science.investigation.evidence.basic", prompt: "Kita ingin membandingkan pengaruh jumlah air pada tanaman. Apa yang sebaiknya dibuat sama?", choices: ["Jenis dan ukuran tanaman", "Jumlah air", "Letak label nama"], correctChoice: "Jenis dan ukuran tanaman" },
    { kind: "choice", id: "science-predict-ice-warm-place", packId: "science.pack.investigation-evidence", lessonId: "science-investigation-evidence", title: "Prediksi es di tempat hangat", description: "Gunakan pengalaman perubahan wujud untuk membuat prediksi.", emoji: "🧊", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: false, skillId: "science.investigation.evidence.basic", prompt: "Es batu diletakkan di tempat yang hangat. Apa prediksi yang paling masuk akal?", choices: ["Es akan mencair", "Es akan menjadi lebih keras", "Es akan tumbuh daun"], correctChoice: "Es akan mencair" },
    { kind: "choice", id: "science-evidence-shadow-times", packId: "science.pack.investigation-evidence", lessonId: "science-investigation-evidence", title: "Bukti dari bayangan", description: "Pilih kesimpulan sederhana dari pengamatan bayangan pada dua waktu.", emoji: "☀️", ageMin: 5, ageMax: 7, difficulty: 3, requiredForStage: false, skillId: "science.investigation.evidence.basic", prompt: "Bayangan tongkat tampak panjang pagi hari dan lebih pendek saat siang. Apa yang ditunjukkan pengamatan itu?", choices: ["Bayangan dapat berubah sepanjang hari", "Tongkat berubah menjadi lebih pendek", "Tanah selalu berpindah tempat"], correctChoice: "Bayangan dapat berubah sepanjang hari" },
    { kind: "matching", id: "science-match-observation-tools-d", packId: "science.pack.investigation-evidence", lessonId: "science-investigation-evidence", title: "Pasangkan alat dan pengamatan", description: "Hubungkan alat sederhana dengan hal yang diukur.", emoji: "📏", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: false, skillId: "science.investigation.evidence.basic", prompt: "Pasangkan alat dengan hal yang diukur", matchItems: [{ label: "Penggaris", pair: "panjang" }, { label: "Panjang", pair: "panjang" }, { label: "Jam", pair: "waktu" }, { label: "Waktu", pair: "waktu" }] },
    { kind: "choice", id: "science-feature-duck-webbed-feet", packId: "science.pack.living-adaptations", lessonId: "science-living-adaptations", title: "Kaki bebek", description: "Hubungkan kaki berselaput dengan gerak di air.", emoji: "🦆", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: true, skillId: "science.living.features_function.basic", prompt: "Bebek memiliki kaki berselaput. Kaki itu membantu bebek terutama saat apa?", choices: ["Berenang di air", "Menggali batu keras", "Memanjat dinding licin"], correctChoice: "Berenang di air" },
    { kind: "choice", id: "science-feature-fish-gills", packId: "science.pack.living-adaptations", lessonId: "science-living-adaptations", title: "Insang ikan", description: "Kenali fungsi sederhana insang pada ikan.", emoji: "🐟", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: false, skillId: "science.living.features_function.basic", prompt: "Ikan menggunakan insang terutama untuk apa?", choices: ["Mengambil oksigen dari air", "Menyimpan biji makanan", "Membuat cahaya matahari"], correctChoice: "Mengambil oksigen dari air" },
    { kind: "choice", id: "science-feature-bird-beak-seeds", packId: "science.pack.living-adaptations", lessonId: "science-living-adaptations", title: "Paruh burung dan biji", description: "Hubungkan bentuk paruh familiar dengan fungsi mengambil makanan.", emoji: "🐦", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: false, skillId: "science.living.features_function.basic", prompt: "Burung kecil memakai paruhnya saat memakan biji. Paruh membantu burung untuk apa?", choices: ["Mengambil makanan", "Mengubah malam menjadi siang", "Membekukan air"], correctChoice: "Mengambil makanan" },
    { kind: "choice", id: "science-feature-cactus-water", packId: "science.pack.living-adaptations", lessonId: "science-living-adaptations", title: "Kaktus menyimpan air", description: "Kenali fungsi batang tebal pada contoh tumbuhan kering.", emoji: "🌵", ageMin: 5, ageMax: 7, difficulty: 3, requiredForStage: false, skillId: "science.living.features_function.basic", prompt: "Batang kaktus yang tebal dapat menyimpan air. Mengapa kemampuan itu berguna di tempat yang jarang hujan?", choices: ["Air dapat digunakan saat lingkungan kering", "Batang membuat hujan turun setiap hari", "Kaktus tidak lagi membutuhkan cahaya"], correctChoice: "Air dapat digunakan saat lingkungan kering" },
    { kind: "matching", id: "science-match-feature-function-d", packId: "science.pack.living-adaptations", lessonId: "science-living-adaptations", title: "Pasangkan ciri dan fungsi", description: "Hubungkan ciri makhluk hidup dengan fungsi familiar.", emoji: "🧩", ageMin: 5, ageMax: 7, difficulty: 3, requiredForStage: false, skillId: "science.living.features_function.basic", prompt: "Pasangkan ciri dengan fungsi sederhananya", matchItems: [{ label: "Sirip ikan", pair: "swim" }, { label: "Membantu berenang", pair: "swim" }, { label: "Akar tumbuhan", pair: "water" }, { label: "Menyerap air", pair: "water" }] },
    { kind: "choice", id: "science-material-raincoat-waterproof", packId: "science.pack.material-design", lessonId: "science-material-design", title: "Bahan jas hujan", description: "Pilih sifat bahan yang cocok untuk menahan air.", emoji: "🌧️", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: true, skillId: "science.materials.design_choice.basic", prompt: "Sifat bahan apa yang paling dibutuhkan untuk membuat jas hujan?", choices: ["Tidak mudah ditembus air", "Mudah menyerap air", "Mudah hancur saat basah"], correctChoice: "Tidak mudah ditembus air" },
    { kind: "choice", id: "science-material-window-transparent", packId: "science.pack.material-design", lessonId: "science-material-design", title: "Bahan jendela", description: "Pilih sifat bahan agar cahaya dapat melewati jendela.", emoji: "🪟", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: false, skillId: "science.materials.design_choice.basic", prompt: "Jendela ingin dibuat agar kita dapat melihat ke luar. Sifat bahan apa yang dibutuhkan?", choices: ["Transparan", "Tidak tembus pandang", "Sangat menyerap air"], correctChoice: "Transparan" },
    { kind: "choice", id: "science-material-towel-absorbent", packId: "science.pack.material-design", lessonId: "science-material-design", title: "Bahan handuk", description: "Pilih sifat bahan yang sesuai untuk mengeringkan air.", emoji: "🧺", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: false, skillId: "science.materials.design_choice.basic", prompt: "Handuk digunakan untuk mengeringkan badan. Sifat bahan apa yang paling berguna?", choices: ["Menyerap air", "Memantulkan semua cahaya", "Selalu mengapung di udara"], correctChoice: "Menyerap air" },
    { kind: "choice", id: "science-material-toy-block-rigid", packId: "science.pack.material-design", lessonId: "science-material-design", title: "Balok mainan kokoh", description: "Pilih sifat bahan untuk balok yang mempertahankan bentuk.", emoji: "🧱", ageMin: 5, ageMax: 7, difficulty: 3, requiredForStage: false, skillId: "science.materials.design_choice.basic", prompt: "Balok susun perlu mempertahankan bentuk saat ditumpuk. Sifat apa yang paling membantu?", choices: ["Kaku dan kokoh", "Sangat lembek", "Larut terkena sedikit air"], correctChoice: "Kaku dan kokoh" },
    { kind: "matching", id: "science-match-material-purpose-d", packId: "science.pack.material-design", lessonId: "science-material-design", title: "Pasangkan sifat dan kegunaan", description: "Hubungkan sifat bahan dengan penggunaan yang sesuai.", emoji: "🔗", ageMin: 5, ageMax: 7, difficulty: 3, requiredForStage: false, skillId: "science.materials.design_choice.basic", prompt: "Pasangkan sifat bahan dengan kegunaannya", matchItems: [{ label: "Tahan air", pair: "rain" }, { label: "Jas hujan", pair: "rain" }, { label: "Transparan", pair: "view" }, { label: "Jendela", pair: "view" }] },
    { kind: "choice", id: "science-weather-dark-clouds-predict", packId: "science.pack.weather-environment-reasoning", lessonId: "science-weather-environment-reasoning", title: "Prediksi dari awan gelap", description: "Gunakan tanda cuaca untuk memilih prediksi sederhana.", emoji: "☁️", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: true, skillId: "science.weather.environment_reasoning.basic", prompt: "Langit menjadi sangat mendung dan awan tampak gelap. Perubahan cuaca apa yang masuk akal untuk diwaspadai?", choices: ["Hujan mungkin turun", "Matahari berubah menjadi es", "Semua pohon langsung berbunga"], correctChoice: "Hujan mungkin turun" },
    { kind: "choice", id: "science-weather-wind-leaves", packId: "science.pack.weather-environment-reasoning", lessonId: "science-weather-environment-reasoning", title: "Tanda angin", description: "Kenali bukti sederhana bahwa udara bergerak.", emoji: "🍃", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: false, skillId: "science.weather.environment_reasoning.basic", prompt: "Daun dan bendera bergerak kuat walau tidak disentuh. Apa penyebab yang paling mungkin?", choices: ["Angin bertiup", "Tanah membeku", "Bulan menarik daun ke atas"], correctChoice: "Angin bertiup" },
    { kind: "choice", id: "science-env-close-tap-effect", packId: "science.pack.weather-environment-reasoning", lessonId: "science-weather-environment-reasoning", title: "Tutup keran", description: "Hubungkan tindakan hemat air dengan akibat langsung.", emoji: "🚰", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: false, skillId: "science.weather.environment_reasoning.basic", prompt: "Apa akibat langsung jika keran ditutup saat tidak dipakai?", choices: ["Lebih sedikit air terbuang", "Air berubah menjadi pasir", "Udara berhenti bergerak"], correctChoice: "Lebih sedikit air terbuang" },
    { kind: "choice", id: "science-env-reuse-container-effect", packId: "science.pack.weather-environment-reasoning", lessonId: "science-weather-environment-reasoning", title: "Gunakan kembali wadah", description: "Pilih alasan sederhana menggunakan kembali benda yang masih layak.", emoji: "♻️", ageMin: 5, ageMax: 7, difficulty: 3, requiredForStage: false, skillId: "science.weather.environment_reasoning.basic", prompt: "Menggunakan kembali wadah yang masih layak dapat membantu lingkungan karena apa?", choices: ["Mengurangi benda yang langsung dibuang", "Membuat semua sampah hilang sendiri", "Menghentikan hujan selamanya"], correctChoice: "Mengurangi benda yang langsung dibuang" },
    { kind: "matching", id: "science-match-weather-action-d", packId: "science.pack.weather-environment-reasoning", lessonId: "science-weather-environment-reasoning", title: "Pasangkan kondisi dan tindakan", description: "Hubungkan kondisi cuaca dengan tindakan sederhana yang sesuai.", emoji: "🌤️", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: false, skillId: "science.weather.environment_reasoning.basic", prompt: "Pasangkan kondisi dengan tindakan yang sesuai", matchItems: [{ label: "Hujan", pair: "umbrella" }, { label: "Gunakan payung", pair: "umbrella" }, { label: "Terik", pair: "shade" }, { label: "Cari tempat teduh", pair: "shade" }] },
    { kind: "choice", id: "science-mixed-plant-wilting", packId: "science.pack.mixed-review-challenge", lessonId: "science-mixed-review-challenge", title: "Tanaman mulai layu", description: "Gunakan konsep kebutuhan tumbuhan untuk memilih pemeriksaan awal.", emoji: "🪴", ageMin: 5, ageMax: 7, difficulty: 3, requiredForStage: true, skillId: "science.mixed_reasoning.review", prompt: "Tanaman dalam pot mulai layu. Hal dasar apa yang masuk akal untuk diperiksa lebih dulu?", choices: ["Apakah mendapat cukup air", "Apakah pot bisa bernyanyi", "Apakah daun terbuat dari logam"], correctChoice: "Apakah mendapat cukup air" },
    { kind: "choice", id: "science-mixed-ice-to-water", packId: "science.pack.mixed-review-challenge", lessonId: "science-mixed-review-challenge", title: "Es menjadi air", description: "Gabungkan pengamatan suhu dan perubahan wujud.", emoji: "💦", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: false, skillId: "science.mixed_reasoning.review", prompt: "Es dibiarkan di meja lalu berubah menjadi air. Perubahan apa yang terjadi?", choices: ["Mencair", "Membeku", "Bertunas"], correctChoice: "Mencair" },
    { kind: "choice", id: "science-mixed-push-cart", packId: "science.pack.mixed-review-challenge", lessonId: "science-mixed-review-challenge", title: "Dorong kereta mainan", description: "Gunakan konsep gaya untuk memilih akibat langsung.", emoji: "🛒", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: false, skillId: "science.mixed_reasoning.review", prompt: "Kereta mainan diam lalu didorong. Apa yang paling mungkin terjadi?", choices: ["Kereta mulai bergerak", "Kereta berubah menjadi tumbuhan", "Kereta membuat air membeku"], correctChoice: "Kereta mulai bergerak" },
    { kind: "choice", id: "science-mixed-sense-bell", packId: "science.pack.mixed-review-challenge", lessonId: "science-mixed-review-challenge", title: "Amati bunyi bel", description: "Pilih indera yang paling sesuai untuk mengamati bunyi.", emoji: "🔔", ageMin: 5, ageMax: 7, difficulty: 2, requiredForStage: false, skillId: "science.mixed_reasoning.review", prompt: "Indera apa yang paling membantu mengetahui apakah bel sedang berbunyi?", choices: ["Pendengaran", "Pengecap", "Penciuman"], correctChoice: "Pendengaran" },
    { kind: "matching", id: "science-match-mixed-review-d", packId: "science.pack.mixed-review-challenge", lessonId: "science-mixed-review-challenge", title: "Pasangkan sebab dan hasil", description: "Hubungkan dua sebab sederhana dengan hasil yang dapat diamati.", emoji: "🧠", ageMin: 5, ageMax: 7, difficulty: 3, requiredForStage: false, skillId: "science.mixed_reasoning.review", prompt: "Pasangkan sebab dengan hasil yang paling sesuai", matchItems: [{ label: "Es dipanaskan", pair: "melt" }, { label: "Es mencair", pair: "melt" }, { label: "Bola didorong", pair: "move" }, { label: "Bola bergerak", pair: "move" }] }
  ]
};
