import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
const games=[
["Math Motion Battle","Jawab soal matematika dengan menulis angka di udara.","01","#25C77A"],["Number Trace Adventure","Ikuti jalur angka dan dapatkan skor lintasan.","02","#3E8BFF"],["Shape Quest","Gambar bentuk dengan satu atau beberapa stroke.","03","#FF9A3D"],["Pattern Race","Lanjutkan pola angka sebelum waktu habis.","04","#8C5CFF"],["Math Warung","Pilih barang, hitung total, dan cari kembalian.","05","#F3B41B"],["Iqro Motion","Latihan Hijaiyah, titik, dan audio.","06","#22A884"],["AirBoard Presenter","Papan tulis dan presentasi tanpa sentuh.","07","#5476FF"],["Dodge Motion","Geser, lompat, dan jongkok menghindari objek.","08","#F35E67"],["Run to Target","Bergerak ke target kiri, kanan, maju, dan mundur.","09","#19A8B7"]];
const rows=games.map(([title,description,index,color])=>`<article class="preview-row" style="--accent:${color}"><b>${index}</b><div class="preview-icon">✦</div><section><h3>${title}</h3><p>${description}</p><span>Internal module · V2 Beta</span></section><button>Buka →</button></article>`).join("");
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Mainlagi TV V2 Preview</title><style>${await readFile("preview/preview.css","utf8")}</style></head><body><header><img src="mainlagi-square.png"><strong>Mainlagi TV</strong><nav>9 aktivitas　Cara kerja　Pilihan Mainlagi</nav><button>Masuk Google</button></header><main><section class="preview-hero"><div><small>SATU KAMERA · SEMBILAN PENGALAMAN</small><h1>Gerak badan.<br><span>Gerak pikiran.</span></h1><p>Sembilan game dan alat interaktif langsung di dalam satu Motion Learning Hub.</p><a href="#games">Pilih permainan</a></div><div class="preview-screen"><b>LIVE MOTION</b><strong>7 + 5</strong><i>Hand + body skeleton</i></div></section><section id="games"><small>SEMUA AKTIVITAS</small><h2>Sembilan module. Satu sistem.</h2>${rows}</section></main></body></html>`;
await mkdir("preview/dist",{recursive:true});
await writeFile("preview/dist/index.html",html);
await copyFile("public/brand/mainlagi-square.png","preview/dist/mainlagi-square.png");
await copyFile("preview/game.html","preview/dist/preflight.html");
console.log("Preview built: preview/dist/index.html and preview/dist/preflight.html");
