-- Mainlagi Expansion Batch 13 — Science/Sains Wave D (subject total 75 -> 100)
-- Adds 25 measured assessed activities across investigation/evidence, living features,
-- material choice, weather/environment reasoning, and mixed Science review.
-- Uses only existing measured matching/choice evidence contracts.
-- Additive/idempotent only; historical attempts, progress, scores, and mastery identities remain unchanged.

insert into public.learning_skills(skill_key,subject_id,title,description,domain,age_min,age_max,active,updated_at) values
('science.investigation.evidence.basic','science','Penyelidikan dan bukti dasar','Membuat prediksi dan memilih perbandingan sederhana dari bukti yang dapat diamati.','science',5,7,true,now()),
('science.living.features_function.basic','science','Ciri dan fungsi makhluk hidup','Menghubungkan ciri familiar hewan atau tumbuhan dengan fungsi sederhananya.','science',5,7,true,now()),
('science.materials.design_choice.basic','science','Pemilihan bahan dasar','Memilih bahan sesuai sifat yang dibutuhkan untuk penggunaan sehari-hari sederhana.','science',5,7,true,now()),
('science.weather.environment_reasoning.basic','science','Penalaran cuaca dan lingkungan','Menghubungkan tanda cuaca dan tindakan menjaga lingkungan dengan akibat sederhana.','science',5,7,true,now()),
('science.mixed_reasoning.review','science','Penalaran sains campuran','Menerapkan beberapa konsep sains dasar dalam tantangan campuran yang terukur.','science',5,7,true,now())
on conflict(skill_key) do update set subject_id=excluded.subject_id,title=excluded.title,description=excluded.description,domain=excluded.domain,age_min=excluded.age_min,age_max=excluded.age_max,active=true,updated_at=now();

insert into public.learning_content_packs(pack_id,subject_id,path_id,stage_id,title,version,age_min,age_max,review_status,active,updated_at) values
('science.pack.investigation-evidence','science','science-discovery-foundations','science-evidence-review-challenge','Investigation and Evidence','1.0.0',5,7,'internal',true,now()),
('science.pack.living-adaptations','science','science-discovery-foundations','science-evidence-review-challenge','Living Features and Functions','1.0.0',5,7,'internal',true,now()),
('science.pack.material-design','science','science-discovery-foundations','science-evidence-review-challenge','Materials for a Purpose','1.0.0',5,7,'internal',true,now()),
('science.pack.weather-environment-reasoning','science','science-discovery-foundations','science-evidence-review-challenge','Weather and Environment Reasoning','1.0.0',5,7,'internal',true,now()),
('science.pack.mixed-review-challenge','science','science-discovery-foundations','science-evidence-review-challenge','Mixed Science Review Challenge','1.0.0',5,7,'internal',true,now())
on conflict(pack_id) do update set subject_id=excluded.subject_id,path_id=excluded.path_id,stage_id=excluded.stage_id,title=excluded.title,version=excluded.version,age_min=excluded.age_min,age_max=excluded.age_max,review_status=excluded.review_status,active=true,updated_at=now();

insert into public.learning_activities(activity_id,subject_id,stage_id,runtime,difficulty,assessment,required_for_stage,motion_optional,star_reward,content_pack_id,lesson_id,mechanic_id,evidence_contract,content_revision,active,updated_at) values
('science-investigate-plant-light','science','science-evidence-review-challenge','tap_choice',2,'assessed',true,false,3,'science.pack.investigation-evidence','science-investigation-evidence','tap_choice','choice_accuracy_v1',1,true,now()),
('science-investigate-fair-water','science','science-evidence-review-challenge','tap_choice',3,'assessed',false,false,3,'science.pack.investigation-evidence','science-investigation-evidence','tap_choice','choice_accuracy_v1',1,true,now()),
('science-predict-ice-warm-place','science','science-evidence-review-challenge','tap_choice',2,'assessed',false,false,3,'science.pack.investigation-evidence','science-investigation-evidence','tap_choice','choice_accuracy_v1',1,true,now()),
('science-evidence-shadow-times','science','science-evidence-review-challenge','tap_choice',3,'assessed',false,false,3,'science.pack.investigation-evidence','science-investigation-evidence','tap_choice','choice_accuracy_v1',1,true,now()),
('science-match-observation-tools-d','science','science-evidence-review-challenge','matching',2,'assessed',false,false,3,'science.pack.investigation-evidence','science-investigation-evidence','matching','matching_accuracy_v1',1,true,now()),
('science-feature-duck-webbed-feet','science','science-evidence-review-challenge','tap_choice',2,'assessed',true,false,3,'science.pack.living-adaptations','science-living-adaptations','tap_choice','choice_accuracy_v1',1,true,now()),
('science-feature-fish-gills','science','science-evidence-review-challenge','tap_choice',2,'assessed',false,false,3,'science.pack.living-adaptations','science-living-adaptations','tap_choice','choice_accuracy_v1',1,true,now()),
('science-feature-bird-beak-seeds','science','science-evidence-review-challenge','tap_choice',2,'assessed',false,false,3,'science.pack.living-adaptations','science-living-adaptations','tap_choice','choice_accuracy_v1',1,true,now()),
('science-feature-cactus-water','science','science-evidence-review-challenge','tap_choice',3,'assessed',false,false,3,'science.pack.living-adaptations','science-living-adaptations','tap_choice','choice_accuracy_v1',1,true,now()),
('science-match-feature-function-d','science','science-evidence-review-challenge','matching',3,'assessed',false,false,3,'science.pack.living-adaptations','science-living-adaptations','matching','matching_accuracy_v1',1,true,now()),
('science-material-raincoat-waterproof','science','science-evidence-review-challenge','tap_choice',2,'assessed',true,false,3,'science.pack.material-design','science-material-design','tap_choice','choice_accuracy_v1',1,true,now()),
('science-material-window-transparent','science','science-evidence-review-challenge','tap_choice',2,'assessed',false,false,3,'science.pack.material-design','science-material-design','tap_choice','choice_accuracy_v1',1,true,now()),
('science-material-towel-absorbent','science','science-evidence-review-challenge','tap_choice',2,'assessed',false,false,3,'science.pack.material-design','science-material-design','tap_choice','choice_accuracy_v1',1,true,now()),
('science-material-toy-block-rigid','science','science-evidence-review-challenge','tap_choice',3,'assessed',false,false,3,'science.pack.material-design','science-material-design','tap_choice','choice_accuracy_v1',1,true,now()),
('science-match-material-purpose-d','science','science-evidence-review-challenge','matching',3,'assessed',false,false,3,'science.pack.material-design','science-material-design','matching','matching_accuracy_v1',1,true,now()),
('science-weather-dark-clouds-predict','science','science-evidence-review-challenge','tap_choice',2,'assessed',true,false,3,'science.pack.weather-environment-reasoning','science-weather-environment-reasoning','tap_choice','choice_accuracy_v1',1,true,now()),
('science-weather-wind-leaves','science','science-evidence-review-challenge','tap_choice',2,'assessed',false,false,3,'science.pack.weather-environment-reasoning','science-weather-environment-reasoning','tap_choice','choice_accuracy_v1',1,true,now()),
('science-env-close-tap-effect','science','science-evidence-review-challenge','tap_choice',2,'assessed',false,false,3,'science.pack.weather-environment-reasoning','science-weather-environment-reasoning','tap_choice','choice_accuracy_v1',1,true,now()),
('science-env-reuse-container-effect','science','science-evidence-review-challenge','tap_choice',3,'assessed',false,false,3,'science.pack.weather-environment-reasoning','science-weather-environment-reasoning','tap_choice','choice_accuracy_v1',1,true,now()),
('science-match-weather-action-d','science','science-evidence-review-challenge','matching',2,'assessed',false,false,3,'science.pack.weather-environment-reasoning','science-weather-environment-reasoning','matching','matching_accuracy_v1',1,true,now()),
('science-mixed-plant-wilting','science','science-evidence-review-challenge','tap_choice',3,'assessed',true,false,3,'science.pack.mixed-review-challenge','science-mixed-review-challenge','tap_choice','choice_accuracy_v1',1,true,now()),
('science-mixed-ice-to-water','science','science-evidence-review-challenge','tap_choice',2,'assessed',false,false,3,'science.pack.mixed-review-challenge','science-mixed-review-challenge','tap_choice','choice_accuracy_v1',1,true,now()),
('science-mixed-push-cart','science','science-evidence-review-challenge','tap_choice',2,'assessed',false,false,3,'science.pack.mixed-review-challenge','science-mixed-review-challenge','tap_choice','choice_accuracy_v1',1,true,now()),
('science-mixed-sense-bell','science','science-evidence-review-challenge','tap_choice',2,'assessed',false,false,3,'science.pack.mixed-review-challenge','science-mixed-review-challenge','tap_choice','choice_accuracy_v1',1,true,now()),
('science-match-mixed-review-d','science','science-evidence-review-challenge','matching',3,'assessed',false,false,3,'science.pack.mixed-review-challenge','science-mixed-review-challenge','matching','matching_accuracy_v1',1,true,now())
on conflict(activity_id) do update set subject_id=excluded.subject_id,stage_id=excluded.stage_id,runtime=excluded.runtime,difficulty=excluded.difficulty,assessment=excluded.assessment,required_for_stage=excluded.required_for_stage,motion_optional=excluded.motion_optional,star_reward=excluded.star_reward,content_pack_id=excluded.content_pack_id,lesson_id=excluded.lesson_id,mechanic_id=excluded.mechanic_id,evidence_contract=excluded.evidence_contract,content_revision=excluded.content_revision,active=true,updated_at=now();

insert into public.learning_activity_skills(activity_id,skill_key,evidence_weight) values
('science-investigate-plant-light','science.investigation.evidence.basic',1),('science-investigate-fair-water','science.investigation.evidence.basic',1),('science-predict-ice-warm-place','science.investigation.evidence.basic',1),('science-evidence-shadow-times','science.investigation.evidence.basic',1),('science-match-observation-tools-d','science.investigation.evidence.basic',1),
('science-feature-duck-webbed-feet','science.living.features_function.basic',1),('science-feature-fish-gills','science.living.features_function.basic',1),('science-feature-bird-beak-seeds','science.living.features_function.basic',1),('science-feature-cactus-water','science.living.features_function.basic',1),('science-match-feature-function-d','science.living.features_function.basic',1),
('science-material-raincoat-waterproof','science.materials.design_choice.basic',1),('science-material-window-transparent','science.materials.design_choice.basic',1),('science-material-towel-absorbent','science.materials.design_choice.basic',1),('science-material-toy-block-rigid','science.materials.design_choice.basic',1),('science-match-material-purpose-d','science.materials.design_choice.basic',1),
('science-weather-dark-clouds-predict','science.weather.environment_reasoning.basic',1),('science-weather-wind-leaves','science.weather.environment_reasoning.basic',1),('science-env-close-tap-effect','science.weather.environment_reasoning.basic',1),('science-env-reuse-container-effect','science.weather.environment_reasoning.basic',1),('science-match-weather-action-d','science.weather.environment_reasoning.basic',1),
('science-mixed-plant-wilting','science.mixed_reasoning.review',1),('science-mixed-ice-to-water','science.mixed_reasoning.review',1),('science-mixed-push-cart','science.mixed_reasoning.review',1),('science-mixed-sense-bell','science.mixed_reasoning.review',1),('science-match-mixed-review-d','science.mixed_reasoning.review',1)
on conflict(activity_id,skill_key) do update set evidence_weight=excluded.evidence_weight;
